name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crblanaru/fastapi:latest,crblanaru/fastapi:v0.0.${{ github.run_number }}
  create-environment:
    runs-on: ubuntu-latest
    needs: [create-image]
    container:
        image: crblanaru/bunnyshell-cli:custom
    steps:
        - name: clone-template
          run: |
            new_id=$( /bunnyshell-cli environments clone --id e3xQywBxBK --token ${{ secrets.BUNNYSHELL_TOKEN }} --name "fast-api-${{ github.run_number }}" | sed -nr 's/EnvironmentID.*\| (.*)/\1/p' )
            echo "new_id=$new_id" >> $GITHUB_ENV
        # need one more step here where I alter the image name for the helm chart by setting an environment variable
        # using sleep to give me time to perform this step manually
        - name: set-env-variable
          run: |
            sleep 30
        - name: deploy-environment
          run: |
            /bunnyshell-cli environments deploy --id ${{ env.new_id }} --token ${{ secrets.BUNNYSHELL_TOKEN }}
        - name: wait-for-deployment
          run: |
            sleep 50
  run-tests:
    runs-on: ubuntu-latest
    needs: [create-image]
    container:
        image: crblanaru/bunnyshell-cli:custom
    steps:
        - name: simple-tests
          run: |
            echo "success"
