name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    container:
        image: crblanaru/bunnyshell-cli:custom
    steps:
        - name: clone-template
          id: clone-template
          run: |
            mkdir ~/.bunnyshell && echo 'outputformat: json' > ~/.bunnyshell/config.yaml
            whoami
            bunnyshell-cli environments list --token ${{ secrets.BUNNYSHELL_TOKEN }}
