name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    container:
        image: bunnyshell/cli
    steps:
        - name: clone-template
          id: clone-template
          run: |
            /bunnyshell-cli environments list --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json
       
